apiVersion: v1
kind: Service
metadata:
  name: micro-postulaciones-deployment-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: micro-postulaciones-deployment