name: Deploy to DO

on:
  workflow_dispatch:
    # Enable manual run
  push:
    branches:
      - main

jobs:

  push_to_registry:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: '${{ secrets.DOCKER_USERNAME }}/micro_postulaciones'

  setup-and-deploy:
    name: Setup and Deploy
    needs: push_to_registry
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 postulacion-ascendere

    - name: Deploy to DigitalOcean Kubernetes
      run: |-
        kustomize build . | kubectl apply -f -
        kubectl patch deployment micro-postulaciones-deployment -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"

    - name: Verify deployment
      run: kubectl rollout status deployment/micro-postulaciones-deployment
