name: Deploy to GKE

on:
  workflow_dispatch:
    # Enable manual run
  push:
    branches:
      - main

#env:
  #PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  #GKE_CLUSTER: postulacion-ascendere
  #GKE_ZONE: us-central1 
  #DEPLOYMENT_NAME: micro-postulaciones-deployment

jobs:

  push_to_registry:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: '${{ secrets.DOCKER_USERNAME }}/micro_postulaciones'
